sudo: required
dist: trusty

language: cpp

env:
  global:
    - OVERRIDE_BOOST_MODULES="--with-python"
  matrix:
    - VERSION=2.2.0

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install nasm

install:
  - git clone https://github.com/nerdvegas/rez.git
  - cd rez
  - python ./install.py -v /tmp/rez
  - cd ..
  - export PATH=/tmp/rez/bin/rez:$PATH
  - mkdir -p /home/travis/packages
  - rez-bind platform
  - rez-bind arch
  - rez-bind os
  - git clone https://github.com/piratecrew/rez-python.git
  - cd rez-python
  - rez-build -i
  - cd ..
  - git clone https://github.com/piratecrew/rez-boost.git
  - cd rez-boost
  - rez-build -i
  - cd ..
  - git clone https://github.com/piratecrew/rez-ilmbase.git
  - cd rez-ilmbase
  - rez-build -i
  - cd ..

script:
  - sed -i s/version.*=.*/version=\"${VERSION}\"/ package.py
  - rez-build -i